[build]
target = "./index.html"
release = true
public_url = "/simple-word-counter/"

[watch]
watch = ["index.html", "src/", "style/"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
]
